
services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: "postgres:15.1-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - shop_postgres:/var/lib/postgresql/data
      - /home/vagrant/services/database:/docker-entrypoint-initdb.d
    networks:
      - internal-network
    deploy:
      placement:
        constraints: [node.role == manager]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - internal-network

  # --- PROXY ---
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Access gateway via http://localhost/gateway and session via http://localhost/session
    configs:
      - source: nginx_conf_v1
        target: /etc/nginx/nginx.conf
    networks:
      - internal-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # --- APP SERVICES ---
  session:
    image: sulaiman3352/session-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - internal-network

  gateway:
    image: sulaiman3352/gateway-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password 
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8087
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
    depends_on:
      - postgres
      - rabbitmq
      - session
    networks:
      - internal-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  hotel:
    image: sulaiman3352/hotel-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotels_db
    networks:
      - internal-network

  loyalty:
    image: sulaiman3352/loyalty-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: balances_db
    networks:
      - internal-network

  booking:
    image: sulaiman3352/booking-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
    networks:
      - internal-network

  report:
    image: sulaiman3352/report-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
    networks:
      - internal-network

  payment:
    image: sulaiman3352/payment-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments_db
    networks:
      - internal-network

volumes:
  shop_postgres:

configs:
  nginx_conf_v1:
    file: ./nginx.conf

networks:
  internal-network:
    external: true
    name: myapp_internal-network

